### ISSUE TITLE
Can't get your examples to work

### ISSUE THREAD

**Issue by randallmlough** [web-ridge/gqlgen-sqlboiler-examples#2]
I can't for the life of me get your social networking example to work. 

Every time I run `go run convert_plugin.go` it results in a panic. However, I've copied the files exactly as you have. 

Panic trace
```sh
go run convert_plugin.go
[convert] get boiler models
[convert] get extra's from schema
[convert] get model with information
[convert] render preload.gotpl
renderError template.gotpl: template: template.gotpl:26:3: executing "template.gotpl" at <reserveImport $.BackendModelsPath>: error calling reserveImport: empty ambient import
[convert] render convert.gotpl
renderError template.gotpl: template: template.gotpl:27:3: executing "template.gotpl" at <reserveImport $.BackendModelsPath>: error calling reserveImport: empty ambient import
[convert] render convert_input.gotpl
renderError template.gotpl: template: template.gotpl:27:3: executing "template.gotpl" at <reserveImport $.BackendModelsPath>: error calling reserveImport: empty ambient import
[convert] render filter.gotpl
renderError template.gotpl: template: template.gotpl:26:3: executing "template.gotpl" at <reserveImport $.BackendModelsPath>: error calling reserveImport: empty ambient import
panic: recursive or concurrent call to RenderToFile detected

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/templates.Render(0xc000137af0, 0xe, 0x0, 0x0, 0xc0001cc1c0, 0x65, 0x101, 0x0, 0x0, 0x0, ...)
        /[MY_ACCOUNT]/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/codegen/templates/templates.go:63 +0xfdf
github.com/99designs/gqlgen/codegen.GenerateCode(0xc0007e1300, 0xc0007e1300, 0x0)
        /Users/randa:8 +0xfb
github.com/99designs/gqlgen/api.Generate(0xc00021c3c0, 0xc000175f48, 0x2, 0x2, 0x0, 0xc000111610)
        /[MY_ACCOUNT]/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/api/generate.go:77 +0x378
main.main()
        /[MY_ACCOUNT]/Desktop/golang/github.com/randallmlough/testing-maria/convert_plugin.go:27 +0x183
exit status 2
make: [helpers] Error 1 (ignored)

```

Here is 1:1 copy of your example https://github.com/randallmlough/sqlboiler-graphql-schema (minus the generated files/dirs since that is where the issue lies)

I added a `Makefile` with each command with a `make gen` command that should execute the operations which you have listed.

SQLBoiler Version: `v4.1.2`

Please let me know what I am doing wrong

**Comment by randallmlough** [comment]
I just found this issue: https://github.com/web-ridge/gqlgen-sqlboiler/issues/3 

I moved the project into my GOPATH (I was using modules beforehand) and that appears to fix it. Is `sqlboiler-graphql-schema` unable to work with go mod / outside of gopath?

**Comment by RichardLindhout** [comment]
Thank you for PR which fixes this!
